server {
    listen 80;
    server_name kinventoryservices.com www.kinventoryservices.com 18.191.181.99;

    root /var/www/kore/kore-inventory;
    index index.html;

    # Proxy para la API (backend en puerto 3000)
    location /api/ {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    # Archivos estáticos (frontend)
    location / {
        try_files $uri $uri/ =404;
    }
}
